---

name: ci

on: [push]

jobs:
  test:
    name: test
    env:
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [{ name: 3.1, value: 3.1.4 }, { name: 3.2, value: 3.2.5 }]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
